// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gcm/gcm.proto

package gcm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	// FCMリクエストURL
	RequestURL string `protobuf:"bytes,1,opt,name=requestURL,proto3" json:"requestURL,omitempty"`
	// FCM認証サーバキー
	ServerKey string `protobuf:"bytes,2,opt,name=serverKey,proto3" json:"serverKey,omitempty"`
	// Sender ID
	SenderID string `protobuf:"bytes,3,opt,name=senderID,proto3" json:"senderID,omitempty"`
	// Do not set to true in production
	InsecureSkipVerify bool `protobuf:"varint,4,opt,name=insecureSkipVerify,proto3" json:"insecureSkipVerify,omitempty"`
	// Firebaseプロジェクトのサービスアカウント(JSON)
	ServiceAccount       string   `protobuf:"bytes,5,opt,name=serviceAccount,proto3" json:"serviceAccount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ef3996f1c1cc671, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetRequestURL() string {
	if m != nil {
		return m.RequestURL
	}
	return ""
}

func (m *Header) GetServerKey() string {
	if m != nil {
		return m.ServerKey
	}
	return ""
}

func (m *Header) GetSenderID() string {
	if m != nil {
		return m.SenderID
	}
	return ""
}

func (m *Header) GetInsecureSkipVerify() bool {
	if m != nil {
		return m.InsecureSkipVerify
	}
	return false
}

func (m *Header) GetServiceAccount() string {
	if m != nil {
		return m.ServiceAccount
	}
	return ""
}

// Parameters はFCMのリクエストと同じ内容を表す。
type Parameters struct {
	CollapseKey          string            `protobuf:"bytes,1,opt,name=collapseKey,proto3" json:"collapseKey,omitempty"`
	DelayWhileIdle       bool              `protobuf:"varint,2,opt,name=delayWhileIdle,proto3" json:"delayWhileIdle,omitempty"`
	ContentAvailable     bool              `protobuf:"varint,5,opt,name=contentAvailable,proto3" json:"contentAvailable,omitempty"`
	MutableContent       bool              `protobuf:"varint,6,opt,name=mutableContent,proto3" json:"mutableContent,omitempty"`
	Data                 map[string]string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Notification         map[string]string `protobuf:"bytes,4,rep,name=notification,proto3" json:"notification,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Parameters) Reset()         { *m = Parameters{} }
func (m *Parameters) String() string { return proto.CompactTextString(m) }
func (*Parameters) ProtoMessage()    {}
func (*Parameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ef3996f1c1cc671, []int{1}
}

func (m *Parameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameters.Unmarshal(m, b)
}
func (m *Parameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameters.Marshal(b, m, deterministic)
}
func (m *Parameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameters.Merge(m, src)
}
func (m *Parameters) XXX_Size() int {
	return xxx_messageInfo_Parameters.Size(m)
}
func (m *Parameters) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameters.DiscardUnknown(m)
}

var xxx_messageInfo_Parameters proto.InternalMessageInfo

func (m *Parameters) GetCollapseKey() string {
	if m != nil {
		return m.CollapseKey
	}
	return ""
}

func (m *Parameters) GetDelayWhileIdle() bool {
	if m != nil {
		return m.DelayWhileIdle
	}
	return false
}

func (m *Parameters) GetContentAvailable() bool {
	if m != nil {
		return m.ContentAvailable
	}
	return false
}

func (m *Parameters) GetMutableContent() bool {
	if m != nil {
		return m.MutableContent
	}
	return false
}

func (m *Parameters) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Parameters) GetNotification() map[string]string {
	if m != nil {
		return m.Notification
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "gcm.Header")
	proto.RegisterType((*Parameters)(nil), "gcm.Parameters")
	proto.RegisterMapType((map[string]string)(nil), "gcm.Parameters.DataEntry")
	proto.RegisterMapType((map[string]string)(nil), "gcm.Parameters.NotificationEntry")
}

func init() { proto.RegisterFile("gcm/gcm.proto", fileDescriptor_1ef3996f1c1cc671) }

var fileDescriptor_1ef3996f1c1cc671 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x51, 0xab, 0xd3, 0x30,
	0x14, 0xc7, 0xe9, 0xba, 0x3b, 0xba, 0x73, 0x55, 0xae, 0xd1, 0x87, 0x38, 0x44, 0xea, 0x15, 0x64,
	0x08, 0xb6, 0xa0, 0x0f, 0x8a, 0x3e, 0xc8, 0xbd, 0xde, 0xa1, 0x43, 0x11, 0xa9, 0xa8, 0xe0, 0x5b,
	0x96, 0x9e, 0x75, 0x61, 0x69, 0x52, 0xd3, 0x74, 0x50, 0x3f, 0x8a, 0x1f, 0xc1, 0x8f, 0xe0, 0xa7,
	0x93, 0xa4, 0xb2, 0x75, 0x9b, 0x2f, 0xbe, 0x25, 0xff, 0x7f, 0xfe, 0x3f, 0xce, 0xc9, 0x39, 0x70,
	0xbd, 0xe0, 0x65, 0x5a, 0xf0, 0x32, 0xa9, 0x8c, 0xb6, 0x9a, 0x84, 0x05, 0x2f, 0xcf, 0x7f, 0x07,
	0x30, 0x7a, 0x8b, 0x2c, 0x47, 0x43, 0xee, 0x01, 0x18, 0xfc, 0xde, 0x60, 0x6d, 0x3f, 0x67, 0xef,
	0x69, 0x10, 0x07, 0xd3, 0x71, 0xd6, 0x53, 0xc8, 0x5d, 0x18, 0xd7, 0x68, 0x36, 0x68, 0xde, 0x61,
	0x4b, 0x07, 0xde, 0xde, 0x09, 0x64, 0x02, 0x51, 0x8d, 0x2a, 0x47, 0x33, 0xbf, 0xa2, 0xa1, 0x37,
	0xb7, 0x77, 0x92, 0x00, 0x11, 0xaa, 0x46, 0xde, 0x18, 0xfc, 0xb4, 0x16, 0xd5, 0x17, 0x34, 0x62,
	0xd9, 0xd2, 0x61, 0x1c, 0x4c, 0xa3, 0xec, 0x1f, 0x0e, 0x79, 0x08, 0x37, 0x1c, 0x58, 0x70, 0xbc,
	0xe0, 0x5c, 0x37, 0xca, 0xd2, 0x13, 0x4f, 0x3c, 0x50, 0xcf, 0x7f, 0x86, 0x00, 0x1f, 0x99, 0x61,
	0x25, 0x5a, 0x34, 0x35, 0x89, 0xe1, 0x94, 0x6b, 0x29, 0x59, 0x55, 0xa3, 0x2b, 0xb1, 0xeb, 0xa0,
	0x2f, 0x39, 0x70, 0x8e, 0x92, 0xb5, 0x5f, 0x57, 0x42, 0xe2, 0x3c, 0x97, 0xe8, 0xfb, 0x88, 0xb2,
	0x03, 0x95, 0x3c, 0x82, 0x33, 0xae, 0x95, 0x45, 0x65, 0x2f, 0x36, 0x4c, 0x48, 0xb6, 0x90, 0xe8,
	0x4b, 0x88, 0xb2, 0x23, 0xdd, 0x31, 0xcb, 0xc6, 0xba, 0xe3, 0xeb, 0xce, 0xa2, 0xa3, 0x8e, 0xb9,
	0xaf, 0x92, 0xc7, 0x30, 0xcc, 0x99, 0x65, 0x34, 0x8c, 0xc3, 0xe9, 0xe9, 0x93, 0x3b, 0x89, 0x1b,
	0xc4, 0xae, 0xf8, 0xe4, 0x8a, 0x59, 0x36, 0x53, 0xd6, 0xb4, 0x99, 0x7f, 0x46, 0x66, 0x70, 0x4d,
	0x69, 0x2b, 0x96, 0x82, 0x33, 0x2b, 0xb4, 0xa2, 0x43, 0x1f, 0xbb, 0x7f, 0x18, 0xfb, 0xd0, 0x7b,
	0xd3, 0xc5, 0xf7, 0x62, 0x93, 0x67, 0x30, 0xde, 0x92, 0xc9, 0x19, 0x84, 0xeb, 0xed, 0xc7, 0xb8,
	0x23, 0xb9, 0x0d, 0x27, 0x1b, 0x26, 0x1b, 0xfc, 0x3b, 0xcf, 0xee, 0xf2, 0x62, 0xf0, 0x3c, 0x98,
	0xbc, 0x82, 0x9b, 0x47, 0xec, 0xff, 0x01, 0x5c, 0xbe, 0xfc, 0xf6, 0xa0, 0x10, 0x76, 0xd5, 0x2c,
	0x12, 0xae, 0xcb, 0xf4, 0x52, 0x4b, 0xfb, 0x63, 0xa6, 0x0a, 0xa1, 0x30, 0x65, 0x95, 0xa8, 0x53,
	0x53, 0x71, 0xb7, 0x8b, 0xbf, 0x06, 0xb7, 0x7a, 0x56, 0x92, 0x55, 0x3c, 0x79, 0xc3, 0xcb, 0xc5,
	0xc8, 0xaf, 0xe8, 0xd3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1a, 0xb6, 0x20, 0x75, 0xb3, 0x02,
	0x00, 0x00,
}
