// Code generated by protoc-gen-go. DO NOT EDIT.
// source: webpush/webpush.proto

package webpush // import "github.com/BoltzEngine/apis/rpc/webpush"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	// WebPush送信者を示すURI(schema must be either mailto or https)
	Subject string `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
	// VAPID生成用の秘密鍵(BASE64url+no padding)
	PrivateKey string `protobuf:"bytes,2,opt,name=privateKey" json:"privateKey,omitempty"`
	// VAPID生成用の公開鍵(BASE64url+no padding)
	PublicKey string `protobuf:"bytes,3,opt,name=publicKey" json:"publicKey,omitempty"`
	// Do not set to true in production
	InsecureSkipVerify   bool     `protobuf:"varint,4,opt,name=insecureSkipVerify" json:"insecureSkipVerify,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_webpush_a431994860bdcb09, []int{0}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Header) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *Header) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Header) GetInsecureSkipVerify() bool {
	if m != nil {
		return m.InsecureSkipVerify
	}
	return false
}

func init() {
	proto.RegisterType((*Header)(nil), "webpush.Header")
}

func init() { proto.RegisterFile("webpush/webpush.proto", fileDescriptor_webpush_a431994860bdcb09) }

var fileDescriptor_webpush_a431994860bdcb09 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x4f, 0x4d, 0x2a,
	0x28, 0x2d, 0xce, 0xd0, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae,
	0xd2, 0x04, 0x46, 0x2e, 0x36, 0x8f, 0xd4, 0xc4, 0x94, 0xd4, 0x22, 0x21, 0x09, 0x2e, 0xf6, 0xe2,
	0xd2, 0xa4, 0xac, 0xd4, 0xe4, 0x12, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x48,
	0x8e, 0x8b, 0xab, 0xa0, 0x28, 0xb3, 0x2c, 0xb1, 0x24, 0xd5, 0x3b, 0xb5, 0x52, 0x82, 0x09, 0x2c,
	0x89, 0x24, 0x22, 0x24, 0xc3, 0xc5, 0x59, 0x50, 0x9a, 0x94, 0x93, 0x99, 0x0c, 0x92, 0x66, 0x06,
	0x4b, 0x23, 0x04, 0x84, 0xf4, 0xb8, 0x84, 0x32, 0xf3, 0x8a, 0x53, 0x93, 0x4b, 0x8b, 0x52, 0x83,
	0xb3, 0x33, 0x0b, 0xc2, 0x52, 0x8b, 0x32, 0xd3, 0x2a, 0x25, 0x58, 0x14, 0x18, 0x35, 0x38, 0x82,
	0xb0, 0xc8, 0x38, 0x39, 0x47, 0xa9, 0xa7, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7,
	0xea, 0x3b, 0xe5, 0xe7, 0x94, 0x54, 0xb9, 0xe6, 0xa5, 0x67, 0xe6, 0xa5, 0xea, 0x27, 0x16, 0x64,
	0x16, 0xeb, 0x17, 0x15, 0x24, 0xc3, 0x3c, 0xb3, 0x8a, 0x49, 0x1c, 0x49, 0x5a, 0x2f, 0xa8, 0x20,
	0x59, 0x2f, 0x3c, 0x35, 0x29, 0xa0, 0xb4, 0x38, 0x23, 0x89, 0x0d, 0xec, 0x4f, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x72, 0x26, 0xdb, 0x80, 0x00, 0x01, 0x00, 0x00,
}
